// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: vla.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_vla_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_vla_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3012000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3012004 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_vla_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_vla_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[3]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_vla_2eproto;
namespace vla {
class Image;
class ImageDefaultTypeInternal;
extern ImageDefaultTypeInternal _Image_default_instance_;
class PredictRequest;
class PredictRequestDefaultTypeInternal;
extern PredictRequestDefaultTypeInternal _PredictRequest_default_instance_;
class PredictResponse;
class PredictResponseDefaultTypeInternal;
extern PredictResponseDefaultTypeInternal _PredictResponse_default_instance_;
}  // namespace vla
PROTOBUF_NAMESPACE_OPEN
template<> ::vla::Image* Arena::CreateMaybeMessage<::vla::Image>(Arena*);
template<> ::vla::PredictRequest* Arena::CreateMaybeMessage<::vla::PredictRequest>(Arena*);
template<> ::vla::PredictResponse* Arena::CreateMaybeMessage<::vla::PredictResponse>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace vla {

enum Image_Encoding : int {
  Image_Encoding_JPEG = 0,
  Image_Encoding_RGB_U8 = 1,
  Image_Encoding_F32_RGB_01 = 2,
  Image_Encoding_Image_Encoding_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::min(),
  Image_Encoding_Image_Encoding_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::max()
};
bool Image_Encoding_IsValid(int value);
constexpr Image_Encoding Image_Encoding_Encoding_MIN = Image_Encoding_JPEG;
constexpr Image_Encoding Image_Encoding_Encoding_MAX = Image_Encoding_F32_RGB_01;
constexpr int Image_Encoding_Encoding_ARRAYSIZE = Image_Encoding_Encoding_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* Image_Encoding_descriptor();
template<typename T>
inline const std::string& Image_Encoding_Name(T enum_t_value) {
  static_assert(::std::is_same<T, Image_Encoding>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function Image_Encoding_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    Image_Encoding_descriptor(), enum_t_value);
}
inline bool Image_Encoding_Parse(
    const std::string& name, Image_Encoding* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<Image_Encoding>(
    Image_Encoding_descriptor(), name, value);
}
// ===================================================================

class Image PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:vla.Image) */ {
 public:
  inline Image() : Image(nullptr) {};
  virtual ~Image();

  Image(const Image& from);
  Image(Image&& from) noexcept
    : Image() {
    *this = ::std::move(from);
  }

  inline Image& operator=(const Image& from) {
    CopyFrom(from);
    return *this;
  }
  inline Image& operator=(Image&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const Image& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Image* internal_default_instance() {
    return reinterpret_cast<const Image*>(
               &_Image_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Image& a, Image& b) {
    a.Swap(&b);
  }
  inline void Swap(Image* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Image* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Image* New() const final {
    return CreateMaybeMessage<Image>(nullptr);
  }

  Image* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Image>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const Image& from);
  void MergeFrom(const Image& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Image* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "vla.Image";
  }
  protected:
  explicit Image(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_vla_2eproto);
    return ::descriptor_table_vla_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  typedef Image_Encoding Encoding;
  static constexpr Encoding JPEG =
    Image_Encoding_JPEG;
  static constexpr Encoding RGB_U8 =
    Image_Encoding_RGB_U8;
  static constexpr Encoding F32_RGB_01 =
    Image_Encoding_F32_RGB_01;
  static inline bool Encoding_IsValid(int value) {
    return Image_Encoding_IsValid(value);
  }
  static constexpr Encoding Encoding_MIN =
    Image_Encoding_Encoding_MIN;
  static constexpr Encoding Encoding_MAX =
    Image_Encoding_Encoding_MAX;
  static constexpr int Encoding_ARRAYSIZE =
    Image_Encoding_Encoding_ARRAYSIZE;
  static inline const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor*
  Encoding_descriptor() {
    return Image_Encoding_descriptor();
  }
  template<typename T>
  static inline const std::string& Encoding_Name(T enum_t_value) {
    static_assert(::std::is_same<T, Encoding>::value ||
      ::std::is_integral<T>::value,
      "Incorrect type passed to function Encoding_Name.");
    return Image_Encoding_Name(enum_t_value);
  }
  static inline bool Encoding_Parse(const std::string& name,
      Encoding* value) {
    return Image_Encoding_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  enum : int {
    kDataFieldNumber = 4,
    kEncodingFieldNumber = 1,
    kHeightFieldNumber = 2,
    kWidthFieldNumber = 3,
  };
  // bytes data = 4;
  void clear_data();
  const std::string& data() const;
  void set_data(const std::string& value);
  void set_data(std::string&& value);
  void set_data(const char* value);
  void set_data(const void* value, size_t size);
  std::string* mutable_data();
  std::string* release_data();
  void set_allocated_data(std::string* data);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_data();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_data(
      std::string* data);
  private:
  const std::string& _internal_data() const;
  void _internal_set_data(const std::string& value);
  std::string* _internal_mutable_data();
  public:

  // .vla.Image.Encoding encoding = 1;
  void clear_encoding();
  ::vla::Image_Encoding encoding() const;
  void set_encoding(::vla::Image_Encoding value);
  private:
  ::vla::Image_Encoding _internal_encoding() const;
  void _internal_set_encoding(::vla::Image_Encoding value);
  public:

  // uint32 height = 2;
  void clear_height();
  ::PROTOBUF_NAMESPACE_ID::uint32 height() const;
  void set_height(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_height() const;
  void _internal_set_height(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // uint32 width = 3;
  void clear_width();
  ::PROTOBUF_NAMESPACE_ID::uint32 width() const;
  void set_width(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_width() const;
  void _internal_set_width(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // @@protoc_insertion_point(class_scope:vla.Image)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr data_;
  int encoding_;
  ::PROTOBUF_NAMESPACE_ID::uint32 height_;
  ::PROTOBUF_NAMESPACE_ID::uint32 width_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_vla_2eproto;
};
// -------------------------------------------------------------------

class PredictRequest PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:vla.PredictRequest) */ {
 public:
  inline PredictRequest() : PredictRequest(nullptr) {};
  virtual ~PredictRequest();

  PredictRequest(const PredictRequest& from);
  PredictRequest(PredictRequest&& from) noexcept
    : PredictRequest() {
    *this = ::std::move(from);
  }

  inline PredictRequest& operator=(const PredictRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline PredictRequest& operator=(PredictRequest&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const PredictRequest& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const PredictRequest* internal_default_instance() {
    return reinterpret_cast<const PredictRequest*>(
               &_PredictRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(PredictRequest& a, PredictRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(PredictRequest* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PredictRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline PredictRequest* New() const final {
    return CreateMaybeMessage<PredictRequest>(nullptr);
  }

  PredictRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<PredictRequest>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const PredictRequest& from);
  void MergeFrom(const PredictRequest& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PredictRequest* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "vla.PredictRequest";
  }
  protected:
  explicit PredictRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_vla_2eproto);
    return ::descriptor_table_vla_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kImagesFieldNumber = 1,
    kLangTokensFieldNumber = 2,
    kStateFieldNumber = 3,
    kNoiseFieldNumber = 4,
    kPrecomputedImgEmbFieldNumber = 6,
    kAttentionMaskFieldNumber = 8,
    kPrevChunkFieldNumber = 9,
    kRequestIdFieldNumber = 5,
    kPrecomputedImgEmbNViewsFieldNumber = 7,
  };
  // repeated .vla.Image images = 1;
  int images_size() const;
  private:
  int _internal_images_size() const;
  public:
  void clear_images();
  ::vla::Image* mutable_images(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::vla::Image >*
      mutable_images();
  private:
  const ::vla::Image& _internal_images(int index) const;
  ::vla::Image* _internal_add_images();
  public:
  const ::vla::Image& images(int index) const;
  ::vla::Image* add_images();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::vla::Image >&
      images() const;

  // repeated int32 lang_tokens = 2;
  int lang_tokens_size() const;
  private:
  int _internal_lang_tokens_size() const;
  public:
  void clear_lang_tokens();
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_lang_tokens(int index) const;
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int32 >&
      _internal_lang_tokens() const;
  void _internal_add_lang_tokens(::PROTOBUF_NAMESPACE_ID::int32 value);
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int32 >*
      _internal_mutable_lang_tokens();
  public:
  ::PROTOBUF_NAMESPACE_ID::int32 lang_tokens(int index) const;
  void set_lang_tokens(int index, ::PROTOBUF_NAMESPACE_ID::int32 value);
  void add_lang_tokens(::PROTOBUF_NAMESPACE_ID::int32 value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int32 >&
      lang_tokens() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int32 >*
      mutable_lang_tokens();

  // repeated float state = 3;
  int state_size() const;
  private:
  int _internal_state_size() const;
  public:
  void clear_state();
  private:
  float _internal_state(int index) const;
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
      _internal_state() const;
  void _internal_add_state(float value);
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
      _internal_mutable_state();
  public:
  float state(int index) const;
  void set_state(int index, float value);
  void add_state(float value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
      state() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
      mutable_state();

  // repeated float noise = 4;
  int noise_size() const;
  private:
  int _internal_noise_size() const;
  public:
  void clear_noise();
  private:
  float _internal_noise(int index) const;
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
      _internal_noise() const;
  void _internal_add_noise(float value);
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
      _internal_mutable_noise();
  public:
  float noise(int index) const;
  void set_noise(int index, float value);
  void add_noise(float value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
      noise() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
      mutable_noise();

  // repeated float precomputed_img_emb = 6;
  int precomputed_img_emb_size() const;
  private:
  int _internal_precomputed_img_emb_size() const;
  public:
  void clear_precomputed_img_emb();
  private:
  float _internal_precomputed_img_emb(int index) const;
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
      _internal_precomputed_img_emb() const;
  void _internal_add_precomputed_img_emb(float value);
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
      _internal_mutable_precomputed_img_emb();
  public:
  float precomputed_img_emb(int index) const;
  void set_precomputed_img_emb(int index, float value);
  void add_precomputed_img_emb(float value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
      precomputed_img_emb() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
      mutable_precomputed_img_emb();

  // repeated uint32 attention_mask = 8;
  int attention_mask_size() const;
  private:
  int _internal_attention_mask_size() const;
  public:
  void clear_attention_mask();
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_attention_mask(int index) const;
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::uint32 >&
      _internal_attention_mask() const;
  void _internal_add_attention_mask(::PROTOBUF_NAMESPACE_ID::uint32 value);
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::uint32 >*
      _internal_mutable_attention_mask();
  public:
  ::PROTOBUF_NAMESPACE_ID::uint32 attention_mask(int index) const;
  void set_attention_mask(int index, ::PROTOBUF_NAMESPACE_ID::uint32 value);
  void add_attention_mask(::PROTOBUF_NAMESPACE_ID::uint32 value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::uint32 >&
      attention_mask() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::uint32 >*
      mutable_attention_mask();

  // repeated float prev_chunk = 9;
  int prev_chunk_size() const;
  private:
  int _internal_prev_chunk_size() const;
  public:
  void clear_prev_chunk();
  private:
  float _internal_prev_chunk(int index) const;
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
      _internal_prev_chunk() const;
  void _internal_add_prev_chunk(float value);
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
      _internal_mutable_prev_chunk();
  public:
  float prev_chunk(int index) const;
  void set_prev_chunk(int index, float value);
  void add_prev_chunk(float value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
      prev_chunk() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
      mutable_prev_chunk();

  // uint64 request_id = 5;
  void clear_request_id();
  ::PROTOBUF_NAMESPACE_ID::uint64 request_id() const;
  void set_request_id(::PROTOBUF_NAMESPACE_ID::uint64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint64 _internal_request_id() const;
  void _internal_set_request_id(::PROTOBUF_NAMESPACE_ID::uint64 value);
  public:

  // uint32 precomputed_img_emb_n_views = 7;
  void clear_precomputed_img_emb_n_views();
  ::PROTOBUF_NAMESPACE_ID::uint32 precomputed_img_emb_n_views() const;
  void set_precomputed_img_emb_n_views(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_precomputed_img_emb_n_views() const;
  void _internal_set_precomputed_img_emb_n_views(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // @@protoc_insertion_point(class_scope:vla.PredictRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::vla::Image > images_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int32 > lang_tokens_;
  mutable std::atomic<int> _lang_tokens_cached_byte_size_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< float > state_;
  mutable std::atomic<int> _state_cached_byte_size_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< float > noise_;
  mutable std::atomic<int> _noise_cached_byte_size_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< float > precomputed_img_emb_;
  mutable std::atomic<int> _precomputed_img_emb_cached_byte_size_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::uint32 > attention_mask_;
  mutable std::atomic<int> _attention_mask_cached_byte_size_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< float > prev_chunk_;
  mutable std::atomic<int> _prev_chunk_cached_byte_size_;
  ::PROTOBUF_NAMESPACE_ID::uint64 request_id_;
  ::PROTOBUF_NAMESPACE_ID::uint32 precomputed_img_emb_n_views_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_vla_2eproto;
};
// -------------------------------------------------------------------

class PredictResponse PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:vla.PredictResponse) */ {
 public:
  inline PredictResponse() : PredictResponse(nullptr) {};
  virtual ~PredictResponse();

  PredictResponse(const PredictResponse& from);
  PredictResponse(PredictResponse&& from) noexcept
    : PredictResponse() {
    *this = ::std::move(from);
  }

  inline PredictResponse& operator=(const PredictResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline PredictResponse& operator=(PredictResponse&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const PredictResponse& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const PredictResponse* internal_default_instance() {
    return reinterpret_cast<const PredictResponse*>(
               &_PredictResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(PredictResponse& a, PredictResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(PredictResponse* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PredictResponse* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline PredictResponse* New() const final {
    return CreateMaybeMessage<PredictResponse>(nullptr);
  }

  PredictResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<PredictResponse>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const PredictResponse& from);
  void MergeFrom(const PredictResponse& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PredictResponse* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "vla.PredictResponse";
  }
  protected:
  explicit PredictResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_vla_2eproto);
    return ::descriptor_table_vla_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kActionChunkFieldNumber = 2,
    kErrorFieldNumber = 7,
    kRequestIdFieldNumber = 1,
    kChunkSizeFieldNumber = 3,
    kActionDimFieldNumber = 4,
    kLatencyMsTotalFieldNumber = 5,
    kLatencyMsInferenceFieldNumber = 6,
    kLatencyMsPrefillFieldNumber = 8,
    kLatencyMsDenoiseFieldNumber = 9,
    kLatencyMsVisionFieldNumber = 10,
  };
  // repeated float action_chunk = 2;
  int action_chunk_size() const;
  private:
  int _internal_action_chunk_size() const;
  public:
  void clear_action_chunk();
  private:
  float _internal_action_chunk(int index) const;
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
      _internal_action_chunk() const;
  void _internal_add_action_chunk(float value);
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
      _internal_mutable_action_chunk();
  public:
  float action_chunk(int index) const;
  void set_action_chunk(int index, float value);
  void add_action_chunk(float value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
      action_chunk() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
      mutable_action_chunk();

  // string error = 7;
  void clear_error();
  const std::string& error() const;
  void set_error(const std::string& value);
  void set_error(std::string&& value);
  void set_error(const char* value);
  void set_error(const char* value, size_t size);
  std::string* mutable_error();
  std::string* release_error();
  void set_allocated_error(std::string* error);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_error();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_error(
      std::string* error);
  private:
  const std::string& _internal_error() const;
  void _internal_set_error(const std::string& value);
  std::string* _internal_mutable_error();
  public:

  // uint64 request_id = 1;
  void clear_request_id();
  ::PROTOBUF_NAMESPACE_ID::uint64 request_id() const;
  void set_request_id(::PROTOBUF_NAMESPACE_ID::uint64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint64 _internal_request_id() const;
  void _internal_set_request_id(::PROTOBUF_NAMESPACE_ID::uint64 value);
  public:

  // uint32 chunk_size = 3;
  void clear_chunk_size();
  ::PROTOBUF_NAMESPACE_ID::uint32 chunk_size() const;
  void set_chunk_size(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_chunk_size() const;
  void _internal_set_chunk_size(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // uint32 action_dim = 4;
  void clear_action_dim();
  ::PROTOBUF_NAMESPACE_ID::uint32 action_dim() const;
  void set_action_dim(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_action_dim() const;
  void _internal_set_action_dim(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // float latency_ms_total = 5;
  void clear_latency_ms_total();
  float latency_ms_total() const;
  void set_latency_ms_total(float value);
  private:
  float _internal_latency_ms_total() const;
  void _internal_set_latency_ms_total(float value);
  public:

  // float latency_ms_inference = 6;
  void clear_latency_ms_inference();
  float latency_ms_inference() const;
  void set_latency_ms_inference(float value);
  private:
  float _internal_latency_ms_inference() const;
  void _internal_set_latency_ms_inference(float value);
  public:

  // float latency_ms_prefill = 8;
  void clear_latency_ms_prefill();
  float latency_ms_prefill() const;
  void set_latency_ms_prefill(float value);
  private:
  float _internal_latency_ms_prefill() const;
  void _internal_set_latency_ms_prefill(float value);
  public:

  // float latency_ms_denoise = 9;
  void clear_latency_ms_denoise();
  float latency_ms_denoise() const;
  void set_latency_ms_denoise(float value);
  private:
  float _internal_latency_ms_denoise() const;
  void _internal_set_latency_ms_denoise(float value);
  public:

  // float latency_ms_vision = 10;
  void clear_latency_ms_vision();
  float latency_ms_vision() const;
  void set_latency_ms_vision(float value);
  private:
  float _internal_latency_ms_vision() const;
  void _internal_set_latency_ms_vision(float value);
  public:

  // @@protoc_insertion_point(class_scope:vla.PredictResponse)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< float > action_chunk_;
  mutable std::atomic<int> _action_chunk_cached_byte_size_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr error_;
  ::PROTOBUF_NAMESPACE_ID::uint64 request_id_;
  ::PROTOBUF_NAMESPACE_ID::uint32 chunk_size_;
  ::PROTOBUF_NAMESPACE_ID::uint32 action_dim_;
  float latency_ms_total_;
  float latency_ms_inference_;
  float latency_ms_prefill_;
  float latency_ms_denoise_;
  float latency_ms_vision_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_vla_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Image

// .vla.Image.Encoding encoding = 1;
inline void Image::clear_encoding() {
  encoding_ = 0;
}
inline ::vla::Image_Encoding Image::_internal_encoding() const {
  return static_cast< ::vla::Image_Encoding >(encoding_);
}
inline ::vla::Image_Encoding Image::encoding() const {
  // @@protoc_insertion_point(field_get:vla.Image.encoding)
  return _internal_encoding();
}
inline void Image::_internal_set_encoding(::vla::Image_Encoding value) {
  
  encoding_ = value;
}
inline void Image::set_encoding(::vla::Image_Encoding value) {
  _internal_set_encoding(value);
  // @@protoc_insertion_point(field_set:vla.Image.encoding)
}

// uint32 height = 2;
inline void Image::clear_height() {
  height_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 Image::_internal_height() const {
  return height_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 Image::height() const {
  // @@protoc_insertion_point(field_get:vla.Image.height)
  return _internal_height();
}
inline void Image::_internal_set_height(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  height_ = value;
}
inline void Image::set_height(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_height(value);
  // @@protoc_insertion_point(field_set:vla.Image.height)
}

// uint32 width = 3;
inline void Image::clear_width() {
  width_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 Image::_internal_width() const {
  return width_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 Image::width() const {
  // @@protoc_insertion_point(field_get:vla.Image.width)
  return _internal_width();
}
inline void Image::_internal_set_width(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  width_ = value;
}
inline void Image::set_width(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_width(value);
  // @@protoc_insertion_point(field_set:vla.Image.width)
}

// bytes data = 4;
inline void Image::clear_data() {
  data_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& Image::data() const {
  // @@protoc_insertion_point(field_get:vla.Image.data)
  return _internal_data();
}
inline void Image::set_data(const std::string& value) {
  _internal_set_data(value);
  // @@protoc_insertion_point(field_set:vla.Image.data)
}
inline std::string* Image::mutable_data() {
  // @@protoc_insertion_point(field_mutable:vla.Image.data)
  return _internal_mutable_data();
}
inline const std::string& Image::_internal_data() const {
  return data_.Get();
}
inline void Image::_internal_set_data(const std::string& value) {
  
  data_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void Image::set_data(std::string&& value) {
  
  data_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:vla.Image.data)
}
inline void Image::set_data(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  data_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:vla.Image.data)
}
inline void Image::set_data(const void* value,
    size_t size) {
  
  data_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:vla.Image.data)
}
inline std::string* Image::_internal_mutable_data() {
  
  return data_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* Image::release_data() {
  // @@protoc_insertion_point(field_release:vla.Image.data)
  return data_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void Image::set_allocated_data(std::string* data) {
  if (data != nullptr) {
    
  } else {
    
  }
  data_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), data,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:vla.Image.data)
}
inline std::string* Image::unsafe_arena_release_data() {
  // @@protoc_insertion_point(field_unsafe_arena_release:vla.Image.data)
  GOOGLE_DCHECK(GetArena() != nullptr);
  
  return data_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void Image::unsafe_arena_set_allocated_data(
    std::string* data) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (data != nullptr) {
    
  } else {
    
  }
  data_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      data, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:vla.Image.data)
}

// -------------------------------------------------------------------

// PredictRequest

// repeated .vla.Image images = 1;
inline int PredictRequest::_internal_images_size() const {
  return images_.size();
}
inline int PredictRequest::images_size() const {
  return _internal_images_size();
}
inline void PredictRequest::clear_images() {
  images_.Clear();
}
inline ::vla::Image* PredictRequest::mutable_images(int index) {
  // @@protoc_insertion_point(field_mutable:vla.PredictRequest.images)
  return images_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::vla::Image >*
PredictRequest::mutable_images() {
  // @@protoc_insertion_point(field_mutable_list:vla.PredictRequest.images)
  return &images_;
}
inline const ::vla::Image& PredictRequest::_internal_images(int index) const {
  return images_.Get(index);
}
inline const ::vla::Image& PredictRequest::images(int index) const {
  // @@protoc_insertion_point(field_get:vla.PredictRequest.images)
  return _internal_images(index);
}
inline ::vla::Image* PredictRequest::_internal_add_images() {
  return images_.Add();
}
inline ::vla::Image* PredictRequest::add_images() {
  // @@protoc_insertion_point(field_add:vla.PredictRequest.images)
  return _internal_add_images();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::vla::Image >&
PredictRequest::images() const {
  // @@protoc_insertion_point(field_list:vla.PredictRequest.images)
  return images_;
}

// repeated int32 lang_tokens = 2;
inline int PredictRequest::_internal_lang_tokens_size() const {
  return lang_tokens_.size();
}
inline int PredictRequest::lang_tokens_size() const {
  return _internal_lang_tokens_size();
}
inline void PredictRequest::clear_lang_tokens() {
  lang_tokens_.Clear();
}
inline ::PROTOBUF_NAMESPACE_ID::int32 PredictRequest::_internal_lang_tokens(int index) const {
  return lang_tokens_.Get(index);
}
inline ::PROTOBUF_NAMESPACE_ID::int32 PredictRequest::lang_tokens(int index) const {
  // @@protoc_insertion_point(field_get:vla.PredictRequest.lang_tokens)
  return _internal_lang_tokens(index);
}
inline void PredictRequest::set_lang_tokens(int index, ::PROTOBUF_NAMESPACE_ID::int32 value) {
  lang_tokens_.Set(index, value);
  // @@protoc_insertion_point(field_set:vla.PredictRequest.lang_tokens)
}
inline void PredictRequest::_internal_add_lang_tokens(::PROTOBUF_NAMESPACE_ID::int32 value) {
  lang_tokens_.Add(value);
}
inline void PredictRequest::add_lang_tokens(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_add_lang_tokens(value);
  // @@protoc_insertion_point(field_add:vla.PredictRequest.lang_tokens)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int32 >&
PredictRequest::_internal_lang_tokens() const {
  return lang_tokens_;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int32 >&
PredictRequest::lang_tokens() const {
  // @@protoc_insertion_point(field_list:vla.PredictRequest.lang_tokens)
  return _internal_lang_tokens();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int32 >*
PredictRequest::_internal_mutable_lang_tokens() {
  return &lang_tokens_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int32 >*
PredictRequest::mutable_lang_tokens() {
  // @@protoc_insertion_point(field_mutable_list:vla.PredictRequest.lang_tokens)
  return _internal_mutable_lang_tokens();
}

// repeated float state = 3;
inline int PredictRequest::_internal_state_size() const {
  return state_.size();
}
inline int PredictRequest::state_size() const {
  return _internal_state_size();
}
inline void PredictRequest::clear_state() {
  state_.Clear();
}
inline float PredictRequest::_internal_state(int index) const {
  return state_.Get(index);
}
inline float PredictRequest::state(int index) const {
  // @@protoc_insertion_point(field_get:vla.PredictRequest.state)
  return _internal_state(index);
}
inline void PredictRequest::set_state(int index, float value) {
  state_.Set(index, value);
  // @@protoc_insertion_point(field_set:vla.PredictRequest.state)
}
inline void PredictRequest::_internal_add_state(float value) {
  state_.Add(value);
}
inline void PredictRequest::add_state(float value) {
  _internal_add_state(value);
  // @@protoc_insertion_point(field_add:vla.PredictRequest.state)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
PredictRequest::_internal_state() const {
  return state_;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
PredictRequest::state() const {
  // @@protoc_insertion_point(field_list:vla.PredictRequest.state)
  return _internal_state();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
PredictRequest::_internal_mutable_state() {
  return &state_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
PredictRequest::mutable_state() {
  // @@protoc_insertion_point(field_mutable_list:vla.PredictRequest.state)
  return _internal_mutable_state();
}

// repeated float noise = 4;
inline int PredictRequest::_internal_noise_size() const {
  return noise_.size();
}
inline int PredictRequest::noise_size() const {
  return _internal_noise_size();
}
inline void PredictRequest::clear_noise() {
  noise_.Clear();
}
inline float PredictRequest::_internal_noise(int index) const {
  return noise_.Get(index);
}
inline float PredictRequest::noise(int index) const {
  // @@protoc_insertion_point(field_get:vla.PredictRequest.noise)
  return _internal_noise(index);
}
inline void PredictRequest::set_noise(int index, float value) {
  noise_.Set(index, value);
  // @@protoc_insertion_point(field_set:vla.PredictRequest.noise)
}
inline void PredictRequest::_internal_add_noise(float value) {
  noise_.Add(value);
}
inline void PredictRequest::add_noise(float value) {
  _internal_add_noise(value);
  // @@protoc_insertion_point(field_add:vla.PredictRequest.noise)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
PredictRequest::_internal_noise() const {
  return noise_;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
PredictRequest::noise() const {
  // @@protoc_insertion_point(field_list:vla.PredictRequest.noise)
  return _internal_noise();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
PredictRequest::_internal_mutable_noise() {
  return &noise_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
PredictRequest::mutable_noise() {
  // @@protoc_insertion_point(field_mutable_list:vla.PredictRequest.noise)
  return _internal_mutable_noise();
}

// uint64 request_id = 5;
inline void PredictRequest::clear_request_id() {
  request_id_ = PROTOBUF_ULONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 PredictRequest::_internal_request_id() const {
  return request_id_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 PredictRequest::request_id() const {
  // @@protoc_insertion_point(field_get:vla.PredictRequest.request_id)
  return _internal_request_id();
}
inline void PredictRequest::_internal_set_request_id(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  
  request_id_ = value;
}
inline void PredictRequest::set_request_id(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _internal_set_request_id(value);
  // @@protoc_insertion_point(field_set:vla.PredictRequest.request_id)
}

// repeated float precomputed_img_emb = 6;
inline int PredictRequest::_internal_precomputed_img_emb_size() const {
  return precomputed_img_emb_.size();
}
inline int PredictRequest::precomputed_img_emb_size() const {
  return _internal_precomputed_img_emb_size();
}
inline void PredictRequest::clear_precomputed_img_emb() {
  precomputed_img_emb_.Clear();
}
inline float PredictRequest::_internal_precomputed_img_emb(int index) const {
  return precomputed_img_emb_.Get(index);
}
inline float PredictRequest::precomputed_img_emb(int index) const {
  // @@protoc_insertion_point(field_get:vla.PredictRequest.precomputed_img_emb)
  return _internal_precomputed_img_emb(index);
}
inline void PredictRequest::set_precomputed_img_emb(int index, float value) {
  precomputed_img_emb_.Set(index, value);
  // @@protoc_insertion_point(field_set:vla.PredictRequest.precomputed_img_emb)
}
inline void PredictRequest::_internal_add_precomputed_img_emb(float value) {
  precomputed_img_emb_.Add(value);
}
inline void PredictRequest::add_precomputed_img_emb(float value) {
  _internal_add_precomputed_img_emb(value);
  // @@protoc_insertion_point(field_add:vla.PredictRequest.precomputed_img_emb)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
PredictRequest::_internal_precomputed_img_emb() const {
  return precomputed_img_emb_;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
PredictRequest::precomputed_img_emb() const {
  // @@protoc_insertion_point(field_list:vla.PredictRequest.precomputed_img_emb)
  return _internal_precomputed_img_emb();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
PredictRequest::_internal_mutable_precomputed_img_emb() {
  return &precomputed_img_emb_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
PredictRequest::mutable_precomputed_img_emb() {
  // @@protoc_insertion_point(field_mutable_list:vla.PredictRequest.precomputed_img_emb)
  return _internal_mutable_precomputed_img_emb();
}

// uint32 precomputed_img_emb_n_views = 7;
inline void PredictRequest::clear_precomputed_img_emb_n_views() {
  precomputed_img_emb_n_views_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 PredictRequest::_internal_precomputed_img_emb_n_views() const {
  return precomputed_img_emb_n_views_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 PredictRequest::precomputed_img_emb_n_views() const {
  // @@protoc_insertion_point(field_get:vla.PredictRequest.precomputed_img_emb_n_views)
  return _internal_precomputed_img_emb_n_views();
}
inline void PredictRequest::_internal_set_precomputed_img_emb_n_views(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  precomputed_img_emb_n_views_ = value;
}
inline void PredictRequest::set_precomputed_img_emb_n_views(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_precomputed_img_emb_n_views(value);
  // @@protoc_insertion_point(field_set:vla.PredictRequest.precomputed_img_emb_n_views)
}

// repeated uint32 attention_mask = 8;
inline int PredictRequest::_internal_attention_mask_size() const {
  return attention_mask_.size();
}
inline int PredictRequest::attention_mask_size() const {
  return _internal_attention_mask_size();
}
inline void PredictRequest::clear_attention_mask() {
  attention_mask_.Clear();
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 PredictRequest::_internal_attention_mask(int index) const {
  return attention_mask_.Get(index);
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 PredictRequest::attention_mask(int index) const {
  // @@protoc_insertion_point(field_get:vla.PredictRequest.attention_mask)
  return _internal_attention_mask(index);
}
inline void PredictRequest::set_attention_mask(int index, ::PROTOBUF_NAMESPACE_ID::uint32 value) {
  attention_mask_.Set(index, value);
  // @@protoc_insertion_point(field_set:vla.PredictRequest.attention_mask)
}
inline void PredictRequest::_internal_add_attention_mask(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  attention_mask_.Add(value);
}
inline void PredictRequest::add_attention_mask(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_add_attention_mask(value);
  // @@protoc_insertion_point(field_add:vla.PredictRequest.attention_mask)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::uint32 >&
PredictRequest::_internal_attention_mask() const {
  return attention_mask_;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::uint32 >&
PredictRequest::attention_mask() const {
  // @@protoc_insertion_point(field_list:vla.PredictRequest.attention_mask)
  return _internal_attention_mask();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::uint32 >*
PredictRequest::_internal_mutable_attention_mask() {
  return &attention_mask_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::uint32 >*
PredictRequest::mutable_attention_mask() {
  // @@protoc_insertion_point(field_mutable_list:vla.PredictRequest.attention_mask)
  return _internal_mutable_attention_mask();
}

// repeated float prev_chunk = 9;
inline int PredictRequest::_internal_prev_chunk_size() const {
  return prev_chunk_.size();
}
inline int PredictRequest::prev_chunk_size() const {
  return _internal_prev_chunk_size();
}
inline void PredictRequest::clear_prev_chunk() {
  prev_chunk_.Clear();
}
inline float PredictRequest::_internal_prev_chunk(int index) const {
  return prev_chunk_.Get(index);
}
inline float PredictRequest::prev_chunk(int index) const {
  // @@protoc_insertion_point(field_get:vla.PredictRequest.prev_chunk)
  return _internal_prev_chunk(index);
}
inline void PredictRequest::set_prev_chunk(int index, float value) {
  prev_chunk_.Set(index, value);
  // @@protoc_insertion_point(field_set:vla.PredictRequest.prev_chunk)
}
inline void PredictRequest::_internal_add_prev_chunk(float value) {
  prev_chunk_.Add(value);
}
inline void PredictRequest::add_prev_chunk(float value) {
  _internal_add_prev_chunk(value);
  // @@protoc_insertion_point(field_add:vla.PredictRequest.prev_chunk)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
PredictRequest::_internal_prev_chunk() const {
  return prev_chunk_;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
PredictRequest::prev_chunk() const {
  // @@protoc_insertion_point(field_list:vla.PredictRequest.prev_chunk)
  return _internal_prev_chunk();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
PredictRequest::_internal_mutable_prev_chunk() {
  return &prev_chunk_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
PredictRequest::mutable_prev_chunk() {
  // @@protoc_insertion_point(field_mutable_list:vla.PredictRequest.prev_chunk)
  return _internal_mutable_prev_chunk();
}

// -------------------------------------------------------------------

// PredictResponse

// uint64 request_id = 1;
inline void PredictResponse::clear_request_id() {
  request_id_ = PROTOBUF_ULONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 PredictResponse::_internal_request_id() const {
  return request_id_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 PredictResponse::request_id() const {
  // @@protoc_insertion_point(field_get:vla.PredictResponse.request_id)
  return _internal_request_id();
}
inline void PredictResponse::_internal_set_request_id(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  
  request_id_ = value;
}
inline void PredictResponse::set_request_id(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _internal_set_request_id(value);
  // @@protoc_insertion_point(field_set:vla.PredictResponse.request_id)
}

// repeated float action_chunk = 2;
inline int PredictResponse::_internal_action_chunk_size() const {
  return action_chunk_.size();
}
inline int PredictResponse::action_chunk_size() const {
  return _internal_action_chunk_size();
}
inline void PredictResponse::clear_action_chunk() {
  action_chunk_.Clear();
}
inline float PredictResponse::_internal_action_chunk(int index) const {
  return action_chunk_.Get(index);
}
inline float PredictResponse::action_chunk(int index) const {
  // @@protoc_insertion_point(field_get:vla.PredictResponse.action_chunk)
  return _internal_action_chunk(index);
}
inline void PredictResponse::set_action_chunk(int index, float value) {
  action_chunk_.Set(index, value);
  // @@protoc_insertion_point(field_set:vla.PredictResponse.action_chunk)
}
inline void PredictResponse::_internal_add_action_chunk(float value) {
  action_chunk_.Add(value);
}
inline void PredictResponse::add_action_chunk(float value) {
  _internal_add_action_chunk(value);
  // @@protoc_insertion_point(field_add:vla.PredictResponse.action_chunk)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
PredictResponse::_internal_action_chunk() const {
  return action_chunk_;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
PredictResponse::action_chunk() const {
  // @@protoc_insertion_point(field_list:vla.PredictResponse.action_chunk)
  return _internal_action_chunk();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
PredictResponse::_internal_mutable_action_chunk() {
  return &action_chunk_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
PredictResponse::mutable_action_chunk() {
  // @@protoc_insertion_point(field_mutable_list:vla.PredictResponse.action_chunk)
  return _internal_mutable_action_chunk();
}

// uint32 chunk_size = 3;
inline void PredictResponse::clear_chunk_size() {
  chunk_size_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 PredictResponse::_internal_chunk_size() const {
  return chunk_size_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 PredictResponse::chunk_size() const {
  // @@protoc_insertion_point(field_get:vla.PredictResponse.chunk_size)
  return _internal_chunk_size();
}
inline void PredictResponse::_internal_set_chunk_size(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  chunk_size_ = value;
}
inline void PredictResponse::set_chunk_size(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_chunk_size(value);
  // @@protoc_insertion_point(field_set:vla.PredictResponse.chunk_size)
}

// uint32 action_dim = 4;
inline void PredictResponse::clear_action_dim() {
  action_dim_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 PredictResponse::_internal_action_dim() const {
  return action_dim_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 PredictResponse::action_dim() const {
  // @@protoc_insertion_point(field_get:vla.PredictResponse.action_dim)
  return _internal_action_dim();
}
inline void PredictResponse::_internal_set_action_dim(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  action_dim_ = value;
}
inline void PredictResponse::set_action_dim(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_action_dim(value);
  // @@protoc_insertion_point(field_set:vla.PredictResponse.action_dim)
}

// float latency_ms_total = 5;
inline void PredictResponse::clear_latency_ms_total() {
  latency_ms_total_ = 0;
}
inline float PredictResponse::_internal_latency_ms_total() const {
  return latency_ms_total_;
}
inline float PredictResponse::latency_ms_total() const {
  // @@protoc_insertion_point(field_get:vla.PredictResponse.latency_ms_total)
  return _internal_latency_ms_total();
}
inline void PredictResponse::_internal_set_latency_ms_total(float value) {
  
  latency_ms_total_ = value;
}
inline void PredictResponse::set_latency_ms_total(float value) {
  _internal_set_latency_ms_total(value);
  // @@protoc_insertion_point(field_set:vla.PredictResponse.latency_ms_total)
}

// float latency_ms_inference = 6;
inline void PredictResponse::clear_latency_ms_inference() {
  latency_ms_inference_ = 0;
}
inline float PredictResponse::_internal_latency_ms_inference() const {
  return latency_ms_inference_;
}
inline float PredictResponse::latency_ms_inference() const {
  // @@protoc_insertion_point(field_get:vla.PredictResponse.latency_ms_inference)
  return _internal_latency_ms_inference();
}
inline void PredictResponse::_internal_set_latency_ms_inference(float value) {
  
  latency_ms_inference_ = value;
}
inline void PredictResponse::set_latency_ms_inference(float value) {
  _internal_set_latency_ms_inference(value);
  // @@protoc_insertion_point(field_set:vla.PredictResponse.latency_ms_inference)
}

// float latency_ms_prefill = 8;
inline void PredictResponse::clear_latency_ms_prefill() {
  latency_ms_prefill_ = 0;
}
inline float PredictResponse::_internal_latency_ms_prefill() const {
  return latency_ms_prefill_;
}
inline float PredictResponse::latency_ms_prefill() const {
  // @@protoc_insertion_point(field_get:vla.PredictResponse.latency_ms_prefill)
  return _internal_latency_ms_prefill();
}
inline void PredictResponse::_internal_set_latency_ms_prefill(float value) {
  
  latency_ms_prefill_ = value;
}
inline void PredictResponse::set_latency_ms_prefill(float value) {
  _internal_set_latency_ms_prefill(value);
  // @@protoc_insertion_point(field_set:vla.PredictResponse.latency_ms_prefill)
}

// float latency_ms_denoise = 9;
inline void PredictResponse::clear_latency_ms_denoise() {
  latency_ms_denoise_ = 0;
}
inline float PredictResponse::_internal_latency_ms_denoise() const {
  return latency_ms_denoise_;
}
inline float PredictResponse::latency_ms_denoise() const {
  // @@protoc_insertion_point(field_get:vla.PredictResponse.latency_ms_denoise)
  return _internal_latency_ms_denoise();
}
inline void PredictResponse::_internal_set_latency_ms_denoise(float value) {
  
  latency_ms_denoise_ = value;
}
inline void PredictResponse::set_latency_ms_denoise(float value) {
  _internal_set_latency_ms_denoise(value);
  // @@protoc_insertion_point(field_set:vla.PredictResponse.latency_ms_denoise)
}

// float latency_ms_vision = 10;
inline void PredictResponse::clear_latency_ms_vision() {
  latency_ms_vision_ = 0;
}
inline float PredictResponse::_internal_latency_ms_vision() const {
  return latency_ms_vision_;
}
inline float PredictResponse::latency_ms_vision() const {
  // @@protoc_insertion_point(field_get:vla.PredictResponse.latency_ms_vision)
  return _internal_latency_ms_vision();
}
inline void PredictResponse::_internal_set_latency_ms_vision(float value) {
  
  latency_ms_vision_ = value;
}
inline void PredictResponse::set_latency_ms_vision(float value) {
  _internal_set_latency_ms_vision(value);
  // @@protoc_insertion_point(field_set:vla.PredictResponse.latency_ms_vision)
}

// string error = 7;
inline void PredictResponse::clear_error() {
  error_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& PredictResponse::error() const {
  // @@protoc_insertion_point(field_get:vla.PredictResponse.error)
  return _internal_error();
}
inline void PredictResponse::set_error(const std::string& value) {
  _internal_set_error(value);
  // @@protoc_insertion_point(field_set:vla.PredictResponse.error)
}
inline std::string* PredictResponse::mutable_error() {
  // @@protoc_insertion_point(field_mutable:vla.PredictResponse.error)
  return _internal_mutable_error();
}
inline const std::string& PredictResponse::_internal_error() const {
  return error_.Get();
}
inline void PredictResponse::_internal_set_error(const std::string& value) {
  
  error_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void PredictResponse::set_error(std::string&& value) {
  
  error_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:vla.PredictResponse.error)
}
inline void PredictResponse::set_error(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  error_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:vla.PredictResponse.error)
}
inline void PredictResponse::set_error(const char* value,
    size_t size) {
  
  error_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:vla.PredictResponse.error)
}
inline std::string* PredictResponse::_internal_mutable_error() {
  
  return error_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* PredictResponse::release_error() {
  // @@protoc_insertion_point(field_release:vla.PredictResponse.error)
  return error_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void PredictResponse::set_allocated_error(std::string* error) {
  if (error != nullptr) {
    
  } else {
    
  }
  error_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), error,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:vla.PredictResponse.error)
}
inline std::string* PredictResponse::unsafe_arena_release_error() {
  // @@protoc_insertion_point(field_unsafe_arena_release:vla.PredictResponse.error)
  GOOGLE_DCHECK(GetArena() != nullptr);
  
  return error_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void PredictResponse::unsafe_arena_set_allocated_error(
    std::string* error) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (error != nullptr) {
    
  } else {
    
  }
  error_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      error, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:vla.PredictResponse.error)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace vla

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::vla::Image_Encoding> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::vla::Image_Encoding>() {
  return ::vla::Image_Encoding_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_vla_2eproto
